linkedin/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls'))
]

myapp/urls.py
from django.urls import path
from . import views

app_name = "myapp"   
urlpatterns = [
    path("", views.HomeView.as_view(), name="homepage"),
    path("register", views.register_request, name="register"),
    path("login", views.login, name="login"),
    path('logout', views.logout, name = 'logout'),
    path("addmember", views.MemberCreateView.as_view(), name='addmember'),
    path("addcompany", views.CompanyCreateView.as_view(), name='addcompany'),
    path('addskill', views.MemberSkillView.as_view(), name='addskill'),
    path('addjob', views.JobCreateView.as_view(), name='addjob'),
    path('makeconnection', views.ConnectionCreateView.as_view(), name='makeconnection'),
    path('updateprofile', views.UpdateProfileView.as_view(), name='updateprofile'),
    path('updatecompany', views.UpdateCompanyView.as_view(), name='updatecompany'),
    path('addeducation', views.EducationCreateView.as_view(), name='addeducation'),
    path('confirmconnection', views.ConnectionConfirmView.as_view(), name='confirmconnection'),
    path('connected/<int:connection_id>', views.connect, name='connected'),
    path('endorseskill/<int:member_id>', views.EndorsementView.as_view(), name='endorseskill'),
    path('viewconnections', views.DisplayConnections.as_view(), name='viewconnections'),
    path('companyhomepage', views.CompanyHomePage.as_view(), name='companyhomepage')
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

# Create your models here.
class Company(models.Model):
    TYPE_CHOICES = (
        ('CS/IT', 'CS/IT'),
        ('Charted Accounted','Charted Accounted'),
        ('Digital Marketing', 'Digital Marketing'),
        ('Digital Content', 'Digital Content'),
        ('Data Sciences', 'Data Sciences'),
        ('Business Developmemt and Sales', 'Buisness Development and Sales'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, unique=True)
    join_date = models.DateField()
    type = models.CharField(max_length=50, choices= TYPE_CHOICES, default='CS/IT')
    establish_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)   

    def __str__(self):
        return f'{self.title}'


class Skill(models.Model):
    title = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.title


class Education(models.Model):   
    title = models.CharField(max_length=200)
   

    def __str__(self):
        return self.title


class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    join_date = models.DateField()
    birth_date = models.DateField(max_length=8)
    skills = models.ManyToManyField(Skill)
    connections = models.ManyToManyField('self', symmetrical=False,through='Connection', blank=True)
    educations = models.ManyToManyField(Education, through='MemberEducation', blank=True )
    joined_company = models.ForeignKey(Company, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(validators=[RegexValidator(regex=r'^\+?92?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")], max_length=17, blank=True) 
    job_position = models.CharField(max_length=200, null=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class MemberEducation(models.Model):
    INSTITUTE_CHOICES = (
        ('Punjab Clg', 'Punjab Clg'),
        ('Fast Nuces','Fast Nuces'),
    )
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    education = models.ForeignKey(Education, on_delete=models.CASCADE)
    institute = models.CharField(max_length=50, choices=INSTITUTE_CHOICES)
    start_date = models.DateField()
    end_date = models.DateField()


class Connection(models.Model):
    STATUS_CHOICES = (
        ('Pending', 'Pending'),
        ('Connected','Connected'),
    )
    sender = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='senders')
    receiver = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='receivers')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='Pending')

    def __str__(self):
        return f'Sender: {self.sender}, Receiver: {self.receiver}'


class PositionVersion(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    job_position = models.CharField(max_length=200)


class Endorsment(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='endorsements')
    endorsed_by = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='endorsed_skills')
    skill = models.ForeignKey(Skill, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.endorse} endorse {self.endorsed} skill'


class Job(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, unique=True)
    description = models.TextField()
    skills = models.ManyToManyField(Skill)

    def __str__(self):
        return f'{self.title}'

myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Company, Connection, Endorsment, Job, Member, MemberEducation


class NewUserForm(UserCreationForm):
    USER_CHOICES = (
        ('Company', 'Company'),
        ('Member', 'Member')
    )
    email = forms.EmailField(required=True)
    user_type = forms.ChoiceField(choices=USER_CHOICES)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2","user_type")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.user_type = self.cleaned_data['user_type']
        if commit:
            user.save()
        return user


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100, widget=forms.PasswordInput)


class DateInput(forms.DateInput):
    input_type = 'date'


class AddMemberForm(ModelForm):
    class Meta:
         model = Member
         exclude = ('user', 'skills', 'connections', 'educations')
         widgets = {
            'join_date': DateInput(),
            'birth_date': DateInput()
         }


class AddCompanyForm(ModelForm):
    class Meta:
        model = Company
        exclude = ('user',)
        widgets = {
            'join_date': DateInput(),
            'establish_date': DateInput()
        }


class MemberSkillForm(ModelForm):
    class Meta:
        model = Member
        fields = ('skills',)
        widgets = {
            'skills': forms.CheckboxSelectMultiple()
        }


class AddEducationForm(ModelForm):
    class Meta:
        model = MemberEducation
        exclude = ('member',)
        widgets = {
            'start_date': DateInput(),
            'end_date': DateInput()
         }


class AddJobForm(ModelForm):
    class Meta:
        model = Job
        exclude = ('company',)
        widgets = {
            'skills': forms.CheckboxSelectMultiple()
        }
        

class MakeConnections(ModelForm):
    class Meta:
        model = Member
        fields = ('connections',)
        widgets = {
            'connections': forms.CheckboxSelectMultiple()
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'instance' in kwargs:
            q1 = Member.objects.exclude(id=kwargs['instance'].id) 
            q1 = q1.exclude(id__in=kwargs['instance'].receivers.values_list('sender_id', flat=True)) 
            q1 = q1.exclude(id__in=kwargs['instance'].senders.filter(status='Connected').values_list('receiver_id', flat=True)) 
            self.fields['connections'].queryset = q1


class ViewConnections(ModelForm):
    class Meta:
        model = Connection
        fields = '__all__'


class AddEndorsementForm(ModelForm):
    class Meta:
        model = Endorsment
        fields = ('skill',)
    
    def __init__(self, *args, **kwargs):
        member_id = kwargs.pop('member_id', None)
        endorser = kwargs.pop('endorser', None)
        super().__init__(*args, **kwargs)
        if member_id and endorser:
            member = Member.objects.get(id=member_id)
            self.fields['skill'].queryset = member.skills.exclude(id__in=endorser.endorsed_skills.values_list('skill_id', flat=True))


class ConnectionViewForm(ModelForm):
    class Meta:
        model = Member
        fields = ('connections',)

myapp/views.py
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from myapp.forms import ConnectionViewForm, NewUserForm, LoginForm
from django.contrib.auth import authenticate, login as login_user, logout as logout_user
from django.contrib import messages
from django.views.generic import View, CreateView
from myapp.models import Member,  Connection, Job
from django.db.models import Q
from myapp.forms import AddMemberForm, AddCompanyForm, MemberSkillForm, AddJobForm, AddEducationForm, MakeConnections, ViewConnections, AddEndorsementForm, ConnectionViewForm


def register_request(request):
    if request.method == 'GET':
        return render(request, 'myapp/register.html', context={'register_form': NewUserForm()})

    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login_user(request, user)
            messages.success(request, 'Registration successful.')
            if request.POST['user_type'] == 'Member':             
                return redirect('myapp:addmember')
            else:
                return redirect('myapp:addcompany')
        return render(request, 'myapp/register.html', context={'register_form': form})


def login(request):
    if request.method == 'GET':
        return render(request, 'myapp/login.html', context={'form': LoginForm()})
    
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(request, username= request.POST['username'], password=request.POST['password'])
            if user is not None:
                login_user(request, user)
                messages.success(request, 'Login Successful')
                return redirect('myapp:homepage')
        messages.error(request, 'Invalid username or password')
        return render(request, 'myapp/login.html', context={'form': form})


def logout(request):
    logout_user(request)
    return redirect('myapp:login')


class MemberCreateView(CreateView):
    form_class = AddMemberForm
    template_name = 'myapp/addmember.html'
    success_url = reverse_lazy('myapp:homepage')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class CompanyCreateView(CreateView):
    form_class = AddCompanyForm
    template_name = 'myapp/addcompany.html'
    success_url = reverse_lazy('myapp:homepage')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class HomeView(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('myapp:login')
        
        if hasattr(request.user,'member'):
            jobs = []
            member_skills_set = set(request.user.member.skills.values_list('id', flat=True))
            for job in Job.objects.all():
                skills_set = set(job.skills.values_list('id', flat=True))
                if skills_set.issubset(member_skills_set):
                    jobs.append(job)
            return render(request, 'myapp/homepage.html', context={'jobs': jobs})
        else:
            return redirect('myapp:companyhomepage')


class MemberSkillView(View):
    def get(self, request):
        return render(request, 'myapp/memberskill.html', context={'form': MemberSkillForm(instance=request.user.member)})
    
    def post(self, request):
        form = MemberSkillForm(request.POST, instance=request.user.member)
        if form.is_valid():
            form.save()
            messages.success(request, f'Updated {request.user.member} Skills successfully')
            return redirect('myapp:homepage')
        return render(request, 'myapp/memberskill.html', context={'form':form})


class JobCreateView(CreateView):
    form_class = AddJobForm
    template_name = 'myapp/addjob.html'
    success_url = reverse_lazy('myapp:homepage')

    def form_valid(self, form):
        form.instance.company = self.request.user.company
        return super().form_valid(form)


class EducationCreateView(CreateView):
    form_class = AddEducationForm
    template_name = 'myapp/addeducation.html'
    success_url = reverse_lazy('myapp:homepage')

    def form_valid(self, form):
        form.instance.member = self.request.user.member
        return super().form_valid(form)


class ConnectionCreateView(View):
    def get(self, request):
        return render(request, 'myapp/makeconnection.html', context={'form': MakeConnections(instance=request.user.member)})
    
    def post(self, request):
        form = MakeConnections(request.POST, instance=request.user.member)
        if form.is_valid():
            form.save()
            messages.success(request, f'Updated {request.user.member} Connections successfully')
            return redirect('myapp:homepage')
        return render(request, 'myapp/makeconnection.html', context={'form':form})


class ConnectionConfirmView(View):
    def get(self, request):
        connection_list = Connection.objects.filter(receiver=request.user.member,status='pending')
        context = {
            'form': ViewConnections(instance=request.user.member),
            'connection_list': connection_list
        }
        return render(request, 'myapp/viewconnection.html', context)


def connect(request, connection_id=id):
    connected = Connection.objects.filter(sender_id=connection_id, receiver_id=request.user.member)
    connected.update(status='Connected')
    return redirect('myapp:homepage')


class UpdateProfileView(View):
    def get(self, request):
        return render(request, 'myapp/updatemember.html', context={'form': AddMemberForm(instance=request.user.member )})

    def post(self, request):
        form = AddMemberForm(request.POST, instance=request.user.member)
        if form.is_valid():
            form.save()
            messages.success(request, f'Updated {request.user.member} Profile successfully')
            return redirect('myapp:homepage')
        return render(request, 'myapp/updatemember.html', context={'form':form})


class UpdateCompanyView(View):
    def get(self, request):
        return render(request, 'myapp/updatecompany.html', context={'form': AddCompanyForm(instance=request.user.company )})

    def post(self, request):
        form = AddCompanyForm(request.POST, instance=request.user.company)
        if form.is_valid():
            form.save()
            messages.success(request, f'Updated {request.user.company} Profile successfully')
            return redirect('myapp:homepage')
        return render(request, 'myapp/updatecompany.html', context={'form':form})


class EndorsementView(View):
    def get(self, request, member_id):
        return render(request, 'myapp/endorseskill.html', context={'form': AddEndorsementForm(member_id=member_id, endorser=request.user.member)})
    
    def post(self, request, member_id):
        form = AddEndorsementForm(request.POST, member_id=member_id, endorser=request.user.member)
        form.instance.member = Member.objects.get(id=member_id)
        form.instance.endorsed_by = request.user.member
        if form.is_valid():
            form.save()
            return redirect('myapp:homepage')
        return render(request, 'myapp/endorseskill.html', context={'form': form})


class DisplayConnections(View):
    def get(self, request):
        context = {
            'form': ConnectionViewForm(instance=request.user.member),
            'connected_members' : Connection.objects.filter((Q(receiver=request.user.member) | Q(sender=request.user.member)), status='connected'),
        }
        return render(request, 'myapp/connected.html', context=context)

class CompanyHomePage(View):
    def get(self, request):
        return render(request, 'myapp/companyhomepage.html')

myapp/templates/myapp/addcompany.html
{% extends 'myapp/base.html' %}
{% block content %} 
{% load crispy_forms_tags %} 
<!--Add Company--> 
<div class="container py-5">
    <h1>Add Company</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}                    
		<button class="btn btn-primary" type="submit">Create</button>
    </form>
</div>
{% endblock content %}

myapp/templates/myapp/addeducation.html
{% extends 'myapp/base.html' %}
{% block content %} 
{% load crispy_forms_tags %} 
<!--Add Job--> 
<div class="container py-5">
    <h1>Add Education</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}                    
		<button class="btn btn-primary" type="submit">Create</button>
    </form>
</div>
{% endblock content %}

myapp/templates/myapp/addjob.html
{% extends 'myapp/base.html' %}
{% block content %} 
{% load crispy_forms_tags %} 
<!--Add Job--> 
<div class="container py-5">
    <h1>Add Job</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}                    
		<button class="btn btn-primary" type="submit">Create</button>
    </form>
</div>
{% endblock content %}

myapp/templates/myapp/addmember.html
{% extends 'myapp/base.html' %}
{% block content %} 
{% load crispy_forms_tags %} 
<!--Add Member--> 
<div class="container py-5">
    <h1>Add Member</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}                    
		<button class="btn btn-primary" type="submit">Create</button>
    </form>
</div>
{% endblock content %}

myapp/templates/myapp/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>LinkedIn</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          {% if not user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'myapp:login' %}">Login</a>
          </li>

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'myapp:register' %}">Register</a>
          </li>
          {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'myapp:homepage' %}">Home</a>
          </li>
          {% if user.member %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'myapp:addskill' %}">Update Skills</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'myapp:addeducation' %}">Update Education</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'myapp:makeconnection' %}">Make Connection</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'myapp:confirmconnection' %}">Connection Requests</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'myapp:viewconnections' %}">Connections</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'myapp:updateprofile' %}">Update Member</a>
          </li>
          {% endif %}
          {% if user.company %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'myapp:addjob' %}">Add Job</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'myapp:updatecompany' %}">Update Company</a>
          </li>
          {% endif %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'myapp:logout' %}">Logout</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}">{{ message }}</div>
    {% endfor %}
    {% endif %}

    {% block content %}{% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

myapp/templates/myapp/endorseskill.html
{% extends 'myapp/base.html' %}
{% block content %} 
{% load crispy_forms_tags %} 
<div class="container py-5">
    <h1>Endorse Skill</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}                    
		<button class="btn btn-primary" type="submit">Endorse</button>
    </form>
</div>
{% endblock content %}

myapp/templates/myapp/homepage.html
{% extends 'myapp/base.html' %}
{% block content %}
<div class="container mt-4">
    {% if user.member %}
    <h1 class="mt-4">Suggested jobs</h1>
    <table class="table">
        <tr>
            <th>Company</th>
            <th>Title</th>
        </tr>
        {% for job in jobs %}
        <tr>
            <td>{{job.company}}</td>
            <td>{{job.title}}</td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</div>
{% endblock content %}

myapp/templates/myapp/login.html
{% extends 'myapp/base.html' %}
{% block content %} 
{% load crispy_forms_tags %} 

<div class="container py-5">
	<h1>Login</h1>
	<form method="POST">
		{% csrf_token %}
		{{ form|crispy }}                    
		<button class="btn btn-primary" type="submit">Login</button>
	</form>
	<p class="text-center">Not have an account? <a href="{% url 'myapp:register' %}">Register</a> instead.</p>
</div>
{% endblock content %}

myapp/templates/myapp/makeconnection.html
{% extends 'myapp/base.html' %}
{% block content %} 
{% load crispy_forms_tags %} 
<!--Make Connection--> 
<div class="container py-5">
    <h1>Make Connections</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}                    
		<button class="btn btn-primary" type="submit">Create</button>
    </form>
</div>
{% endblock content %}

myapp/templates/myapp/memberskill.html
{% extends 'myapp/base.html' %}
{% block content %} 
{% load crispy_forms_tags %} 
<!--Member Skill--> 
<div class="container py-5">
    <h1>Add Skill</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}                    
		<button class="btn btn-primary" type="submit">Create</button>
    </form>
</div>
{% endblock content %}

myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}
{% block content %} 
{% load crispy_forms_tags %} 
<!--Register--> 
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="{% url 'myapp:login' %}">login</a> instead.</p>
</div>
{% endblock content %}

myapp/templates/myapp/updatecompany.html
{% extends 'myapp/base.html' %}
{% block content %} 
{% load crispy_forms_tags %} 
<div class="container py-5">
    <h1>Update Company</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}                    
		<button class="btn btn-primary" type="submit">Update</button>
    </form>
</div>
{% endblock content %}

myapp/templates/myapp/updatemember.html
{% extends 'myapp/base.html' %}
{% block content %} 
{% load crispy_forms_tags %} 
<!--Add Member--> 
<div class="container py-5">
    <h1>Update Member</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}                    
		<button class="btn btn-primary" type="submit">Update</button>
    </form>
</div>
{% endblock content %}

myapp/templates/myapp/viewconnection.html
{% extends 'myapp/base.html' %}
{% block content %} 
{% load crispy_forms_tags %} 
<!--View Connection--> 
<div class="container py-5">
    <h1>Accept Connections</h1>
    <table class="table">
        {% for connection in connection_list %}
        <tr>
            <td>{{connection.sender}}</td>
            <td><a href="connected/{{connection.sender.id}}">Accept</a></td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock content %}